services:
    influxdb:
        image: influxdb:2
        container_name: influxdb
        ports:
            - "8086:8086"
        volumes:
            - ./influxdb/data:/var/lib/influxdb2
            - ./influxdb/config:/etc/influxdb2

        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ORG=zombiedef
            - DOCKER_INFLUXDB_INIT_BUCKET=zombiedef

        env_file:
            - ./.env
